### PR TITLE
Add python version of sbp2json to test numba sbp parsing

### PR DESCRIPTION
**Pull request by silverjam**
Pairs with https://github.com/swift-nav/libsbp/pull/667

### CODE REVIEW

File: piksi_tools/sbp2json.py [hunk 1]
```diff
@@ -7,7 +7,7 @@
 import io
 
 import numpy as np
-import ujson
+import json
```
Comment (silverjam) [inline piksi_tools/sbp2json.py]: What affect does this have on the speed of sbp2json?

Comment (silverjam) [reply piksi_tools/sbp2json.py]: I wonder if we can make this a mode selection, either be compatible with Haskell, or be fast, `ujson` was selected because it's supposed the fastest Python JSON library.

Comment (pmiettinen) [reply piksi_tools/sbp2json.py]: In this current incarnation `ujson` is actually the slowest by huge margin. Suspicious if there was some unknown effect in place during the `ujson` test since it's so bad. In some messages it's suffering from this https://github.com/esnme/ultrajson/issues/221 so throwing the exception probably has some effect but hard to say how much without more investigation.

Default `json` is on par or even slightly faster than Haskell.

```
pasi@pasi-linux:~/swiftnav/libsbp/tmp$ time PYTHONPATH=../python/ python ../../piksi_tools/piksi_tools/sbp2json.py < 0001.sbp > jit_long.json

real    2m20.205s
user    2m13.684s
sys     0m3.036s

pasi@pasi-linux:~/swiftnav/libsbp/tmp$ time runhaskell ../haskell/main/SBP2PRETTYJSON.hs < ./0001.sbp > hask_pretty.json

real    2m29.290s
user    2m2.616s
sys     0m18.148s

pasi@pasi-linux:~/swiftnav/libsbp/tmp$ time PYTHONPATH=../python/ python ../../piksi_tools/piksi_tools/sbp2json.py < 0001.sbp > jit_ujson.json

real    6m19.622s
user    6m11.772s
sys     0m3.236s
```

Comment (pmiettinen) [reply piksi_tools/sbp2json.py]: If it really goes to max recursion multiple times, the result is not probably comparable.

Comment (pmiettinen) [reply piksi_tools/sbp2json.py]:
```
pasi@pasi-linux:~/swiftnav/libsbp/tmp$ time runhaskell ../haskell/main/SBP2JSON.hs < ./0001.sbp > hask.json

real    0m29.567s
user    0m12.680s
sys     0m10.464s
```

Mode/options selection should be investigated.

Comment (pmiettinen) [reply piksi_tools/sbp2json.py]: Note: disabling element sorting in `sbp2json.py` produced only ~20s better result.

Comment (pmiettinen) [reply piksi_tools/sbp2json.py]: This is with `ujson` when using native python float, looks better

```
pasi@pasi-linux:~/swiftnav/libsbp/tmp$ time PYTHONPATH=../python/ python ../../piksi_tools/piksi_tools/sbp2json.py < 0001.sbp > jit.json

real    0m39.281s
user    0m34.704s
sys     0m2.456s
```

Comment (pmiettinen) [reply piksi_tools/sbp2json.py]: This is with `json` when using native python float

```
pasi@pasi-linux:~/swiftnav/libsbp/tmp$ time PYTHONPATH=../python/ python ../../piksi_tools/piksi_tools/sbp2json.py < 0001.sbp > jit.json

real    0m56.106s
user    0m49.220s
sys     0m2.560s
```

**Comment by pmiettinen** [comment]
`round(dec.Decimal(o), abs(d.as_tuple().exponent)).to_eng_string()` doesn't work on 2.7

```
AttributeError: 'float' object has no attribute 'to_eng_string'
```

**Comment by silverjam** [comment]
I'm not able to get json output from this script at the moment:
```
python ./piksi_tools/sbp2json.py <data5m.bin 
# ... no output
```

**Comment by pmiettinen** [comment]
@silverjam - Could you provide details on your environment? I can't reproduce either on Ubuntu or OSX.

```
macbuild-pasi:tmp pasi$ pwd
/mnt/users/pasi/swiftnav/libsbp/tmp
macbuild-pasi:tmp pasi$ PYTHONPATH=../python/ python ../../piksi_tools/piksi_tools/sbp2json.py  < 0001.sbp
{"crc":39656,"length":46,"msg_type":175,"payload":"AHJ0Y21fb3V0AGFudF9kZXNjcmlwdG9yAEhYQ0dQUzUwMCAgICAgICBOT05FAA==","preamble":85,"sender":45490,"setting":"rtcm_out\u0000ant_descriptor\u0000HXCGPS500       NONE\u0000","status":0}
{"crc":34718,"length":31,"msg_type":175,"payload":"AHJ0Y21fb3V0AHJjdl9kZXNjcmlwdG9yAFBJS1NJAA==","preamble":85,"sender":45490,"setting":"rtcm_out\u0000rcv_descriptor\u0000PIKSI\u0000","status":0}
{"crc":6522,"length":75,"msg_type":175,"payload":"AHRjcF9zZXJ2ZXIxAG1vZGUATk1FQSBPVVQAZW51bTpEaXNhYmxlZCxSVENNdjMgSU4sTk1FQSBPVVQsU0JQLFJUQ012MyBPVVQA","preamble":85,"sender":45490,"setting":"tcp_server1\u0000mode\u0000NMEA OUT\u0000enum:Disabled,RTCMv3 IN,NMEA OUT,SBP,RTCMv3 OUT\u0000","status":0}
...
```

Note that `sbp.jit` is not in the `PACKAGES` list when running `python setup.py install` so `PYTHONPATH` is required. Although even without it the script should output `ImportError`.

**Comment by pmiettinen** [comment]
Also if your log file is not huge, please copy it here so I can try with that one.

**Comment by silverjam** [comment]
Tested with a docker container just to rule out environment issues:
```shell
# Ran
docker run --rm -it ubuntu:bionic /bin/bash

## Then inside container ran:

# Update, install basic tools
apt-get update
apt install python3-pip
apt install git vim
apt install llvm-7-dev

# Clone the repos
mkdir work
cd work
git clone -b pmiettinen/esd-1158-benchmark https://github.com/swift-nav/libsbp
git clone -b silverjam/sbp2json https://github.com/swift-nav/piksi_tools

pip3 install -r /work/libsbp/python/requirements.txt
pip3 install -r /work/piksi_tools/requirements.txt

# Removed dep on libsbp branch silverjam/numba-jit2
vim /work/piksi_tools/requirements.txt

pip3 install -r /work/piksi_tools/requirements.txt

# Generate parse_float .so module
cd /work/libsbp/python/sbp/jit/
python3 parse_float.py

# Outside the container:
docker ps # --> find container name
docker cp /tmp/sbp.log  contaier_name:/work/
docker cp ~/dev/piksi_tools/data1m.bin contaier_name:/work/

# Back inside container
cd /work
PYTHONPATH=$PWD/libsbp/python python3 piksi_tools/piksi_tools/sbp2json.py <data1m.bin
# ... no output ...

apt install wget
wget https://github.com/swift-nav/libsbp/releases/download/v2.5.4/sbp_linux_tools.tar.gz
tar xvfz sbp_linux_tools.tar.gz
./sbp2json <data1m.bin
# ... output ...

./sbp2json <sbp.log
# ... output ...
PYTHONPATH=$PWD/libsbp/python python3 piksi_tools/piksi_tools/sbp2json.py <sbp.log
# ... no output ...
```

The files:
- [data1m.bin.zip](https://github.com/swift-nav/piksi_tools/files/3154530/data1m.bin.zip)
- [sbp.log.zip](https://github.com/swift-nav/piksi_tools/files/3154531/sbp.log.zip)

**Comment by pmiettinen** [comment]
`sbp.log` is working fine both inside and outside the docker. Not sure why it shows empty output for you, maybe you mistakenly ran with `data1m.bin`?

`data1m.bin` is not working in either environments and I suspect it's not a valid SBP binary stream:
- Sure Haskell `sbp2json` produces output but if you look at it closely:
    1. sender ID is random
    2. msg_type is random ie. doesn't match the known SBP message IDs
    3. JSON fields are not expanded as is the case with `sbp.log`
    3. `sbp2prettyjson` doesn't output anything as it discards messages with failed CRC while `sbp2json` forces them to SBP base type
    4. All of the above indicates that `sbp2json` just occasionally finds a byte matching the expected preamble and then forces the following bytes to the base SBP pattern
- Original `serial_link.py` also produces an empty file

**Comment by silverjam** [comment]
@pmiettinen 😱😱😱😱😱-- sorry Pasi, indeed, `data1m.bin` is just a random binary stream, I thought it was a valid SBP stream, this tool scores the entropy of a file (near 1 should be completely random):

```
❯ ./build/entrospy ../piksi_tools/data1m.bin
../piksi_tools/data1m.bin: score: 0.999978

❯ ./build/entrospy /tmp/sbp.log
/tmp/sbp.log: score: 0.876948
``` 

I think this should be a bug in the Haskell `sbp2json` then, not sure what the value is of forcing random blobs into the base SBP type, especially if they fail the CRC.

**Comment by silverjam** [comment]
OK, let's merge once https://github.com/swift-nav/libsbp/pull/667 is in.
